-d E:\FPGA_PD\impl\gwsynthesis\pendulum_fpga.vg
-p GW2A-18C-PBGA256-8
-pn GW2A-LV18PG256C8/I7
-cst E:\FPGA_PD\src\pendulum_fpga.cst
-cfg E:\FPGA_PD\impl\pnr\device.cfg
-sdc E:\FPGA_PD\src\pendulum_fpga.sdc
-bit
-tr
-ph
-timing
-cst_error
-convert_sdp32_36_to_sdp16_18
-correct_hold 1
-route_maxfan 23
-global_freq 100.000
